# 000-playbook.yml
---
- hosts: all
  gather_facts: true

  vars:
    tb_hostname: "{{ lookup('env', 'TB_HOSTNAME') }}"
    home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Execute tasks
      include_tasks: "{{ task_file }}"
      loop:
        - 100-set-hostname.yml
        - 200-install-packages.yml
        - 300-gnome.yml
        - 400-install-apps.yml
        - 500-repos.yml
        - 600-golang.yml
        - 900-others.yml
      loop_control:
        loop_var: task_file
      tags: 
        - always
